### ISSUE TITLE
Running in hydra doesn't seem to load the rails environment

### ISSUE THREAD

**Issue by jwhitmire** [ngauthier/hydra#3]
I've got a project I'm not that far along on, but I wanted to use it to play with hydra.  The specs run just fine outside of hydra, but I get in hydra it can't find ActionController making me think it's not properly loading the rails environment when running in hydra.  I can't seem to find any other setup stuff I need to do, let me know what I missed.

http://gist.github.com/369577

**Comment by ngauthier** [comment]
So the new RSpec thing is to just write:

```
require 'spec_helper'
```

at the top of your test files. Since Hydra runs a spec file individually, you need to properly find and load spec_helper, like this:

```
require 'pathname'
require Pathname(__FILE__).ascend { |d|
  h = d + 'spec_helper.rb'; break h if h.file? }
```

You can just try putting this in one spec file, then make a Hydra task that only runs that file. If it works, you should add those lines to the top of all of your spec files.

You can also try:

```
Hydra::TestTask.new('hydra:spec') do |t|
  t.verbose = true
  require 'spec/spec_helper'
  t.add_files 'spec/**/*_spec.rb'
end
```

**Comment by jwhitmire** [comment]
Nick, thanks for the response, but this didn't change anything.  I added the require changes to all of my model/controller specs, verified they still pass outside of hydra, and still get the unknown constant on ActionController when I try to run it using hydra.

Isn't it still running inside the test environment?  It feels like it doesn't yet have an environment loaded, but I may be misinterpreting what I'm seeing.  I'd love to use this for work, but I need to get it running on this project first.  Any advice would be helpful, thanks.

**Comment by ngauthier** [comment]
Hydra won't force the test environment. Try it with RAILS_ENV=test.

**Comment by jwhitmire** [comment]
I had already done that and it didn't make a difference.  :(  I'll try to play with it more a bit later.  Do you have a working sample app somewhere I could use to compare setups?

**Comment by ngauthier** [comment]
Thoughtbot's Factory Girl uses RSpec, and you can simply add a Hydra task to it for the rspec files and it works. So you can compare with that:

http://github.com/thoughtbot/factory_girl

**Comment by jwhitmire** [comment]
Thanks Nick.  I have it working in factory_girl, I'll see if I can get it working on my project as well and let you know.

**Comment by mattscilipoti** [comment]
See another possible solution in Issue #1

**Comment by ebrett** [comment]
Any luck finding a solution for this?  I am having the same problem.

**Comment by ngauthier** [comment]
Yes, this was solved with my comment above. Set RAILS_ENV=test when you run Hydra.

Also: http://wiki.github.com/ngauthier/hydra/why-isnt-it-working

-Nick

**Comment by ebrett** [comment]
Still doesn't work for me.  http://gist.github.com/379349

Any suggestions for what to look at first are appreciated.

-brett

**Comment by ngauthier** [comment]
can you please send me a gist of the top few lines of:
spec/controllers/admin/hotseats_controller_spec.rb

It's probably an issue with how you require spec helper. Outlined here:
http://wiki.github.com/ngauthier/hydra/why-isnt-it-working

**Comment by ebrett** [comment]
At the moment it looks like that shown above (i.e. require 'pathname' et.al.) but originally it looked like this:

require File.expand_path(File.dirname(**FILE**) + '/../../spec_helper')

Same problem, either way.

**Comment by ngauthier** [comment]
Does your spec helper boot your environment? If not, have the Hydra test task setup "environment" as a pre-requisite task.
Hydra::TestTask.new('hydra:spec' => ['environment'])

-Nick

**Comment by jwhitmire** [comment]
Nick, Setting the RAILS_ENV didn't fix it for me, but adding the dependency on 'environment' in the rake task did.  That's the part I was missing, and in hindsight should have caught earlier.  Now it's working great.  Thanks for the help.

**Comment by ngauthier** [comment]
awesome! I added it to the wiki.

**Comment by ebrett** [comment]
Yes, setting the pre-req worked for me too - now I'm having problems with the search specs (using thinking_sphinx) - will let you know when I fix it!

**Comment by ebrett** [comment]
OK, that turned into just a problem with a local name in our search partial - 'link' clashed with something in rake (although only with hydra, so odd) - Rspec stories all pass now - now working on Cucumber...

**Comment by ebrett** [comment]
We're using Cucumber 0.4.4 - shall look at upgrading before going further

**Comment by ebrett** [comment]
but, FYI, here is the error for 0.4.4 http://gist.github.com/380533

**Comment by jwhitmire** [comment]
The only thing I had to do to get cucumber working for me, was to include the require for rspec in my env.rb.  Just adding: 

```
require 'spec/rails'
```

Then everything worked perfectly.  I am on cucumber 0.6.4 though, so maybe there is something with the older version of the gem.
